apiVersion: v1
kind: Secret
metadata:
  name: net-identity-allocator-postgres
  namespace: mac-allocator
type: Opaque
stringData:
  POSTGRES_DB: cmxsafemac_ipv6
  POSTGRES_USER: allocator
  POSTGRES_PASSWORD: change-me-in-production
  POSTGRES_HOST: net-identity-allocator-postgres
  POSTGRES_PORT: "5432"
  POSTGRES_SSLMODE: disable
